#!/usr/bin/env bash

# exit on first failure
set -e

restore_configs
opt_set MOTHERBOARD BOARD_RAMPS4DUE_EFB
opt_enable S_CURVE_ACCELERATION EEPROM_SETTINGS
opt_set E0_AUTO_FAN_PIN 8
opt_set EXTRUDER_AUTO_FAN_SPEED 100
exec_test $1 $2 "RAMPS4DUE_EFB S_CURVE_ACCELERATION EEPROM_SETTINGS"

restore_configs
opt_set MOTHERBOARD BOARD_RADDS
opt_enable_adv Z_TRIPLE_STEPPER_DRIVERS Z_TRIPLE_ENDSTOPS
pins_set RAMPS X_MAX_PIN -1
pins_set RAMPS Y_MAX_PIN -1
opt_add_adv Z2_MAX_PIN 2
opt_add_adv Z3_MAX_PIN 3
opt_enable USE_XMAX_PLUG
opt_enable USE_YMAX_PLUG
exec_test $1 $2 "RADDS Z_TRIPLE"
